tutorial: add QEMU details
tpm2-software/tpm2-software.github.io pull request #51
Opened 2020-10-19 18:16 UTC by williamcroberts

Recently, I had to dig into how to set up QEMU with a virtualized TPM2.0
device to debug a potential issue in the in-kernel resource manager
(/dev/tpmrm0). Their is a quite a bit of information on setting up QEMU,
and a TPM device, it seemed to be lacking in setting up the TPM2.0
device. The crux was the subtle and easy to overlook --tpm2 option
to the SWTPM.

Build a simple tutorial to highlight a setup using TPM2.0.

Signed-off-by: William Roberts <william.c.roberts@intel.com>

2020-10-19 19:10 UTC, idesai requested changes

2020-10-19 19:10 UTC, idesai commented on _posts/2020-10-19-QEMU.md
> +Now to start the guest with a virtualized TPM2.0 device. To do this, one needs to start the SWTPM simulator in tpm2 mode, like so:
```suggestion
Now start the guest with a virtualized TPM2.0 device. To do this, one needs to start the SWTPM simulator in tpm2 mode, like so:
```

2020-10-19 19:10 UTC, idesai commented on _posts/2020-10-19-QEMU.md
> +**Note the --tpm2 option**
```suggestion
```

2020-10-19 19:10 UTC, idesai commented on _posts/2020-10-19-QEMU.md
> +mkdir /tmp/mytpm1
consider renaming mytpm1 to emulated_tpm throughout.

2020-10-19 19:10 UTC, idesai commented on _posts/2020-10-19-QEMU.md
> +
Consider adding information:
Test if the emulated TPM device is available by listing the device nodes in the /dev/ directory.
```consle
ls /dev/tpm*
```

2020-10-19 19:24 UTC, idesai commented
@williamcroberts consider renaming the file to "TPM2 virtualization with QEMU" or something to that effect.

2020-10-20 09:06 UTC, wamserma requested changes

2020-10-20 09:06 UTC, wamserma commented on _posts/2020-10-19-QEMU.md
> +Now to start the guest with a virtualized TPM2.0 device. To do this, one needs to start the SWTPM simulator in tpm2 mode, like so:
The code block following here is missing the code fences (backticks) and thus isn't rendered properly.

2020-10-28 14:08 UTC, williamcroberts commented on _posts/2020-10-19-QEMU.md
> +**Note the --tpm2 option**
That was the part that took me awhile to find, so I really want to highlight since all the other documents leave this option out as they were targeted for 1.1.

2020-10-28 14:16 UTC, williamcroberts commented on _posts/2020-10-19-QEMU.md
> +**Note the --tpm2 option**
Ill put it right in the opening statement about the command.

2020-11-05 13:47 UTC, merged